{% set name = "cptec-subsaz" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cptec-subsaz-{{ version }}.tar.gz
  sha256: 7e4668662a0ba70b8b4e073e0f2c75051a40566ddfe7730e60ebb4d0776461bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - pandas
    - xarray
    - requests
    - matplotlib-base
    - scipy
    - netcdf4

test:
  imports:
    - subsaz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sazonal.readthedocs.io/en/latest/index.html
  dev_url: https://sazonal.readthedocs.io/en/latest/index.html
  doc_url: https://sazonal.readthedocs.io/en/latest/index.html
  summary: Módulo para distribuição do Modelo SubSazonal do CPTEC.
  license: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - framework-CPTEC
